### ISSUE TITLE
yarn start fails

### ISSUE THREAD

**Issue by tljstewart** [box/box-ui-elements-demo#35]
looks like its failing on `fsevent` which says is optional, but it also fails on `yarn start --no-optional` and `yarn start --ignore-optional` 

yarn run v1.22.19
$ yarn install && BABEL_ENV=dev NODE_ENV=dev node --max_old_space_size=8192 node_modules/webpack-dev-server/bin/webpack-dev-server.js --mode development
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "@hapi/address@^2.0.0".
warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "axios@^0.18.1".
warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "color@^3.1.2".
warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "draft-js@^0.10.1".
warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "formik@^2.0.0".
warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "ilib-tree-node@^1.2.0".
warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "immutable@^3.7.4".
warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "message-accumulator@^2.1.1".
warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "mousetrap@^1.6.3".
warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "query-string@5.1.1".
warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "react-beautiful-dnd@^9.0.2".
warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "react-draggable@^3.3.0".
warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "react-intl@^2.9.0".
warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "tabbable@^1.1.2".
warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "uuid@^3.3.2".
warning " > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".
[4/4] Building fresh packages...
warning Error running install script for optional dependency: "/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@19.3.0 | darwin | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for \"/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v111-darwin-arm64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v111-darwin-arm64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v111-darwin-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@19.3.0 (node-v111 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v111-darwin-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@19.3.0 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@19.3.0 | darwin | arm64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tljstewart/.node-gyp/19.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/tljstewart/.node-gyp/19.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/tljstewart/.node-gyp/19.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 22.1.0
gyp ERR! command \"/opt/homebrew/Cellar/node/19.3.0/bin/node\" \"/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64\" \"--napi_version=8\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v111\"
gyp ERR! cwd /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents
gyp ERR! node -v v19.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/19.3.0/bin/node /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64/fse.node --module_name=fse --module_path=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Darwin 22.1.0
node-pre-gyp ERR! command \"/opt/homebrew/Cellar/node/19.3.0/bin/node\" \"/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents
node-pre-gyp ERR! node -v v19.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/opt/homebrew/Cellar/node/19.3.0/bin/node /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64/fse.node --module_name=fse --module_path=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)"
info This module is OPTIONAL, you can safely ignore this error
error /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass
Output:
Building: /opt/homebrew/Cellar/node/19.3.0/bin/node /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/opt/homebrew/Cellar/node/19.3.0/bin/node',
gyp verb cli   '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@19.3.0 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 19.3.0
gyp verb command install [ '19.3.0' ]
gyp verb install input version string "19.3.0"
gyp verb install installing version: 19.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 19.3.0
gyp verb build dir attempting to create "build" dir: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tljstewart/.node-gyp/19.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/tljstewart/.node-gyp/19.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/tljstewart/.node-gyp/19.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable standalone_static_library in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 22.1.0
gyp ERR! command "/opt/homebrew/Cellar/node/19.3.0/bin/node" "/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass
gyp ERR! node -v v19.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tsuresh2188** [comment]
> looks like its failing on `fsevent` which says is optional, but it also fails on `yarn start --no-optional` and `yarn start --ignore-optional`
> 
> yarn run v1.22.19 $ yarn install && BABEL_ENV=dev NODE_ENV=dev node --max_old_space_size=8192 node_modules/webpack-dev-server/bin/webpack-dev-server.js --mode development [1/4] Resolving packages... [2/4] Fetching packages... [3/4] Linking dependencies... warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "@hapi/address@^2.0.0". warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "axios@^0.18.1". warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "color@^3.1.2". warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "draft-js@^0.10.1". warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "formik@^2.0.0". warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "ilib-tree-node@^1.2.0". warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "immutable@^3.7.4". warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "message-accumulator@^2.1.1". warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "mousetrap@^1.6.3". warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "query-string@5.1.1". warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "react-beautiful-dnd@^9.0.2". warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "react-draggable@^3.3.0". warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "react-intl@^2.9.0". warning " > box-ui-elements@12.0.0-beta.9" has incorrect peer dependency "tabbable@^1.1.2". warning " > box-ui-elements@12.0.0-beta.9" has unmet peer dependency "uuid@^3.3.2". warning " > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0". [4/4] Building fresh packages... warning Error running install script for optional dependency: "/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents: Command failed. Exit code: 1 Command: node install Arguments: Directory: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents Output: node-pre-gyp info it worked if it ends with ok node-pre-gyp info using node-pre-gyp@0.12.0 node-pre-gyp info using node@19.3.0 | darwin | arm64 node-pre-gyp WARN Using request for node-pre-gyp https download node-pre-gyp info check checked for "/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64/fse.node" (not found) node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v111-darwin-arm64.tar.gz node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v111-darwin-arm64.tar.gz node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v111-darwin-arm64.tar.gz node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@19.3.0 (node-v111 ABI, unknown) (falling back to source compile with node-gyp) node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v111-darwin-arm64.tar.gz gyp info it worked if it ends with ok gyp info using node-gyp@3.8.0 gyp info using node@19.3.0 | darwin | arm64 gyp info ok gyp info it worked if it ends with ok gyp info using node-gyp@3.8.0 gyp info using node@19.3.0 | darwin | arm64 gyp info spawn /usr/local/bin/python2 gyp info spawn args [ gyp info spawn args '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/gyp/gyp_main.py', gyp info spawn args 'binding.gyp', gyp info spawn args '-f', gyp info spawn args 'make', gyp info spawn args '-I', gyp info spawn args '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/build/config.gypi', gyp info spawn args '-I', gyp info spawn args '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/addon.gypi', gyp info spawn args '-I', gyp info spawn args '/Users/tljstewart/.node-gyp/19.3.0/include/node/common.gypi', gyp info spawn args '-Dlibrary=shared_library', gyp info spawn args '-Dvisibility=default', gyp info spawn args '-Dnode_root_dir=/Users/tljstewart/.node-gyp/19.3.0', gyp info spawn args '-Dnode_gyp_dir=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp', gyp info spawn args '-Dnode_lib_file=/Users/tljstewart/.node-gyp/19.3.0/<(target_arch)/node.lib', gyp info spawn args '-Dmodule_root_dir=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents', gyp info spawn args '-Dnode_engine=v8', gyp info spawn args '--depth=.', gyp info spawn args '--no-parallel', gyp info spawn args '--generator-output', gyp info spawn args 'build', gyp info spawn args '-Goutput_dir=.' gyp info spawn args ] gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp gyp ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1 gyp ERR! stack at ChildProcess.onCpExit (/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/lib/configure.js:345:16) gyp ERR! stack at ChildProcess.emit (node:events:513:28) gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:293:12) gyp ERR! System Darwin 22.1.0 gyp ERR! command "/opt/homebrew/Cellar/node/19.3.0/bin/node" "/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64/fse.node" "--module_name=fse" "--module_path=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v111" gyp ERR! cwd /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents gyp ERR! node -v v19.3.0 gyp ERR! node-gyp -v v3.8.0 gyp ERR! not ok node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/19.3.0/bin/node /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64/fse.node --module_name=fse --module_path=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1) node-pre-gyp ERR! stack at ChildProcess. (/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29) node-pre-gyp ERR! stack at ChildProcess.emit (node:events:513:28) node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1098:16) node-pre-gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:304:5) node-pre-gyp ERR! System Darwin 22.1.0 node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/19.3.0/bin/node" "/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build" node-pre-gyp ERR! cwd /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents node-pre-gyp ERR! node -v v19.3.0 node-pre-gyp ERR! node-pre-gyp -v v0.12.0 node-pre-gyp ERR! not ok Failed to execute '/opt/homebrew/Cellar/node/19.3.0/bin/node /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64/fse.node --module_name=fse --module_path=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/fsevents/lib/binding/Release/node-v111-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)" info This module is OPTIONAL, you can safely ignore this error error /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass: Command failed. Exit code: 1 Command: node scripts/build.js Arguments: Directory: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass Output: Building: /opt/homebrew/Cellar/node/19.3.0/bin/node /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library= gyp info it worked if it ends with ok gyp verb cli [ gyp verb cli '/opt/homebrew/Cellar/node/19.3.0/bin/node', gyp verb cli '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js', gyp verb cli 'rebuild', gyp verb cli '--verbose', gyp verb cli '--libsass_ext=', gyp verb cli '--libsass_cflags=', gyp verb cli '--libsass_ldflags=', gyp verb cli '--libsass_library=' gyp verb cli ] gyp info using node-gyp@3.8.0 gyp info using node@19.3.0 | darwin | arm64 gyp verb command rebuild [] gyp verb command clean [] gyp verb clean removing "build" directory gyp verb command configure [] gyp verb check python checking for Python executable "python2" in the PATH gyp verb `which` succeeded python2 /usr/local/bin/python2 gyp verb check python version `/usr/local/bin/python2 -c "import sys; print "2.7.18 gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j gyp verb get node dir no --target version specified, falling back to host node version: 19.3.0 gyp verb command install [ '19.3.0' ] gyp verb install input version string "19.3.0" gyp verb install installing version: 19.3.0 gyp verb install --ensure was passed, so won't reinstall if already installed gyp verb install version is already installed, need to check "installVersion" gyp verb got "installVersion" 9 gyp verb needs "installVersion" 9 gyp verb install version is good gyp verb get node dir target node version installed: 19.3.0 gyp verb build dir attempting to create "build" dir: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/build gyp verb build dir "build" dir needed to be created? /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/build gyp verb build/config.gypi creating config file gyp verb build/config.gypi writing out config file: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/build/config.gypi gyp verb config.gypi checking for gypi file: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/config.gypi gyp verb common.gypi checking for gypi file: /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/common.gypi gyp verb gyp gyp format was not specified; forcing "make" gyp info spawn /usr/local/bin/python2 gyp info spawn args [ gyp info spawn args '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/gyp/gyp_main.py', gyp info spawn args 'binding.gyp', gyp info spawn args '-f', gyp info spawn args 'make', gyp info spawn args '-I', gyp info spawn args '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass/build/config.gypi', gyp info spawn args '-I', gyp info spawn args '/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/addon.gypi', gyp info spawn args '-I', gyp info spawn args '/Users/tljstewart/.node-gyp/19.3.0/include/node/common.gypi', gyp info spawn args '-Dlibrary=shared_library', gyp info spawn args '-Dvisibility=default', gyp info spawn args '-Dnode_root_dir=/Users/tljstewart/.node-gyp/19.3.0', gyp info spawn args '-Dnode_gyp_dir=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp', gyp info spawn args '-Dnode_lib_file=/Users/tljstewart/.node-gyp/19.3.0/<(target_arch)/node.lib', gyp info spawn args '-Dmodule_root_dir=/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass', gyp info spawn args '-Dnode_engine=v8', gyp info spawn args '--depth=.', gyp info spawn args '--no-parallel', gyp info spawn args '--generator-output', gyp info spawn args 'build', gyp info spawn args '-Goutput_dir=.' gyp info spawn args ] gyp: Undefined variable standalone_static_library in binding.gyp while trying to load binding.gyp gyp ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1 gyp ERR! stack at ChildProcess.onCpExit (/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/lib/configure.js:345:16) gyp ERR! stack at ChildProcess.emit (node:events:513:28) gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:293:12) gyp ERR! System Darwin 22.1.0 gyp ERR! command "/opt/homebrew/Cellar/node/19.3.0/bin/node" "/Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" gyp ERR! cwd /Users/tljstewart/projects/repos/box/scratch/box-ui-elements-demo/node_modules/node-sass gyp ERR! node -v v19.3.0 gyp ERR! node-gyp -v v3.8.0 gyp ERR! not ok Build failed with error code: 1 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[Timothy Stewart](https://github.com/tljstewart) - Hi [Timothy Stewart - What did you do to make this run, i am also getting the same error
